Mobile Implementation: Issue List TIle UI
scorelab/LabelLab pull request #666
Opened 2022-08-14 13:41 UTC by M-A-D-A-R-A

# Description
Issue List TIle UI

<img src="https://user-images.githubusercontent.com/56160262/184539670-cae0e9a3-bef6-4294-833e-266129bb8735.jpeg"  width=40% height=40%>
<img src="https://user-images.githubusercontent.com/56160262/184539725-e7448150-5ae4-4211-a703-7b0812145af3.jpeg"  width=40% height=40%>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

*Test Configuration*:

- Firmware version: Windows
- Hardware: SM M426B
- SDK: Flutter SDK (v 3.0.2)

Also, include screenshots of the app for verification and reviewing purposes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-15 09:11 UTC, amlannandy requested changes
UI is not right. Margin and spacing are all over the place. The issues are obvious in the screenshot you've posted itself. Please pay some attention and fix them.

2022-08-15 09:11 UTC, amlannandy commented on labellab_mobile/lib/widgets/issue_list_tile.dart
> +
Remove the blank line on 193

2022-08-15 09:11 UTC, amlannandy commented on labellab_mobile/lib/widgets/issue_list_tile.dart
>    Color _getBackgroundColor(String category) {
Variable name should be `priority` or something similar. `category` does not make sense here.

2022-08-15 09:11 UTC, amlannandy commented on labellab_mobile/lib/widgets/issue_list_tile.dart
> +                            // mainAxisAlignment: MainAxisAlignment.center,
Remove the comment

2022-08-15 09:44 UTC, amlannandy commented on labellab_mobile/lib/widgets/issue_list_tile.dart
>    Color _getBackgroundColor(String category) {
If it's a priority specific function, name the variable `priority` otherwise something generic like `type`.

2022-08-15 18:47 UTC, M-A-D-A-R-A commented
@amlannandy please review.

2022-08-16 04:05 UTC, amlannandy approved these changes
Look good to me. Nice work 👍🏻

2022-08-16 04:05 UTC, merged