Tag user in comments
scorelab/LabelLab pull request #672
Opened 2022-09-04 15:15 UTC by M-A-D-A-R-A

# Description
Tag user functionality in the message input field
<img src="https://user-images.githubusercontent.com/56160262/188320550-28903de6-72ee-4e04-90c8-46e0ba16e5ea.jpeg"  width=50% height=50%>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Test Configuration:

- Firmware version: Windows
- Hardware: SM M426B
- SDK: Flutter SDK (v 3.0.2)

Also, include screenshots of the app for verification and reviewing purposes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-04 15:18 UTC, M-A-D-A-R-A commented
@amlannandy as of now i just added the SS and opened an issue #673 will make the necessary changes with respect to that.

2022-09-05 03:33 UTC, amlannandy requested changes
1. Fix the left padding in the user mention list popup. You can even see it in the screenshot itself. Also, wrap it in a card component or give a slight light gray border. It's mixing into the rest of the screen otherwise.
2. Add a screen recording showing the functionality.

2022-09-05 03:33 UTC, amlannandy commented on labellab_mobile/lib/labellab_app.dart
> +          //darkTheme: ThemeData.dark(),
Remove the commented line

2022-09-06 08:12 UTC, amlannandy commented
@M-A-D-A-R-A I'd recommend that you don't wait until the end of the week to make the changes. Do so as quickly as time permits, as this is the final week.

2022-09-06 16:57 UTC, M-A-D-A-R-A commented
> @M-A-D-A-R-A I'd recommend that you don't wait until the end of the week to make the changes. Do so as quickly as time permits, as this is the final week.

Updated the comment with video. please review

2022-09-06 17:09 UTC, amlannandy commented
@M-A-D-A-R-A
1. Add padding on the left side of the text field. I shouldn't have to point out obvious issues like this. Pay attention to your work. I had already pointed this out in the last sync-up anyway.
2. The existing comment text should be there in the field during edit mode. Again something obvious you should have caught yourself.
3. Just wrap the whole user mention list in a card widget.  Similar to how all the popups in the app look. Why put spacing between the mentions like this? Just looks weird.

I keep repeating this again and again but please carefully review your work. I shouldn't have to spoon-feed simple stuff like this to you.

2022-09-07 04:29 UTC, amlannandy commented
> > @M-A-D-A-R-A
> > 
> > 1. Add padding on the left side of the text field. I shouldn't have to point out obvious issues like this. Pay attention to your work. I had already pointed this out in the last sync-up anyway.
> > 2. The existing comment text should be there in the field during edit mode. Again something obvious you should have caught yourself.
> > 3. Just wrap the whole user mention list in a card widget.  Similar to how all the popups in the app look. Why put spacing between the mentions like this? Just looks weird.
> > 
> > I keep repeating this again and again but please carefully review your work. I shouldn't have to spoon-feed simple stuff like this to you.
> 
> Sorry was not able to review it properly, done 1,2 changes but in 3 the package is providing us to give a widget to the list view builder, i.e we only need to implement the Container, a particular tile, package reference [here](https://github.com/fayeed/flutter_mentions/blob/6fe2f0aa559765995d07ff84dfec05b91254b98a/lib/src/option_list.dart#L32). Im attaching a SS of how the UI looks as of now please suggest the request changes.
> 
> <img alt="" width="240" src="https://user-images.githubusercontent.com/56160262/188713757-8b1ad05a-9df4-49ab-bab0-de6e99f0ef7f.jpeg">

Add padding around the user avatar inside user mention list item. Similar to how it looks in comment list tile.

2022-09-08 09:15 UTC, amlannandy approved these changes

2022-09-08 09:15 UTC, merged